name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs: 
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to wally
        env:
          WALLY_AUTH: ${{ secrets.WALLY_AUTH_TOKEN }}
        run: |
            mkdir ~/.wally
            printenv WALLY_AUTH > ~/.wally/auth.toml
  
      - name: Push update to wally
        run: wally publish
